debug

diff --git a/.github/workflows/devsecops.yml b/.github/workflows/devsecops.yml
--- a/.github/workflows/devsecops.yml
+++ b/.github/workflows/devsecops.yml
@@ -107,7 +107,13 @@ jobs:
       run: |
         kubectl auth can-i create configmaps -n kube-system
 
-    
+    - name: Debug - Check AWS CLI Version
+      run: aws --version
+  
+    - name: Debug - Check aws-iam-authenticator presence
+      run: which aws-iam-authenticator || echo "aws-iam-authenticator not found"
+        
+
     - name: Terraform Init
       run: terraform init
 
